version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./src:/app/src
    ports:
    - 8080:8080
    networks:
      - backend-network
      - elk-network

  mongodb:
    image: mongo:latest
    ports:
    - 27017:27017
    volumes:
    - ./data/mongo:/data/db
    networks:
      - backend-network
      - mongo-network

  cache:
    image: redis:latest
    ports:
    - 6380:6379
    networks:
      - redis-network
      - backend-network

  cache-gui:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: cache
    ports:
      - '8081:8081'
    networks:
      - redis-network

networks:
  elk-network:
    external:
      name: elk8.1-network
  backend-network:
    driver: bridge
  redis-network:
    driver: bridge
  mongo-network:
    driver: bridge